[package]
name = "GameEngine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
winit = "0.29.2"
wgpu = "0.18.0"
env_logger = "0.10.0"
sdl2="0.35.2"
rand="0.8.5"